export const MESSAGE = {
    NOT_TOKEN: 'Not token',
    TOKEN_NOT_VALID: 'Token not valid',
    NOT_USER: 'Not user',
    NOT_POST: 'Not post',
    WRONG_EMAIL_OR_PHONE: 'Wrong email or phone',
    WRONG_EMAIL_OR_PASSWORD: 'Wrong email or password',
    EMAIL_ALREADY_EXISTS: 'User with this email is already exists',
    NOT_AUTHOR_POST: 'There is no author who wrote this post',
    UNIQUE_TITLE: 'Title must by a unique',
    BAD_AUTHOR_ID: 'AuthorId is not correct',
    BAD_POST_ID: 'PostId is not correct',
    USER_DELETE_SUCCESSFULLY: 'User deleted successfully',
    USER_UPDATE_SUCCESSFULLY: 'User update successfully',
    POST_TEXT_UPDATED_SUCCESSFULLY: 'Post text updated successfully',
    BY_USER: 'We will be waiting for you later',
    NOT_COMMENT_AUTHOR_ID: 'Not comment by this authorId',
    NOT_COMMENT_ID: 'Not comment by this id',
    LIKE: 'like',
    DISLIKE: 'dislike',
    GOOD_DEAL: 'is good deal!!!',
    THANK_YOU_FOR: 'Thank you for',
    YOU_PASSWORD_UPDATED_SUCCESSFULLY: ' password updated successfully',
    TO_BIG_PHOTO_FILE: 'Photo file if to big',
    WRONG_FILE_FORMAT: 'Wrong file format',
};
